apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: towkxhp8r-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:ac0f0c685995c7e95a0801313bacbc3badf15f67@sha256:5bd5902f9c218bd65b617f5c01a1e597a0f458d4de47ebae4daa1ed4b96519b1
          name: container-image
